[package]
name = "goldenai"
version = "0.1.0"
edition = "2024"
description = "GoldenTech AI Python SDK"
authors = ["Guangyu He <guangyu.he@golden-tech.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "goldenai"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["abi3-py310"] }
#pyo3-async-runtimes = { version = "0.25", features = ["attributes", "tokio-runtime"] }
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.98"
openssl = { version = "0.10.72", features = ["vendored"] }

[features]
extension-module = ["pyo3/extension-module"]
